# 1.Convert List to 1D A

In [4]:
import numpy as np

ls = [12.23, 13.32, 100, 36.32]
numpy_array = np.array(ls)

print("Orginal list:", ls)
print("One-dimensional numpy array:",numpy_array)

Orginal list: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23  13.32 100.    36.32]


# 2.Create 3x3 Matrix (2?10)

In [5]:
ls2 = np.arange(2, 11)

matrix = ls2.reshape(3,3)

print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#  3.Null Vector (10) & Update Sixth Value

In [10]:
null_vector = np.zeros(10)
null_vector[6] = 11
print(null_vector)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


# 4. Array from 12 to 38

In [12]:
ls3 = np.arange(12, 38)
print(ls3)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


# 5.Convert Array to Float Type

In [19]:
int_array = np.array([1,2,3,4])
float_array = int_array.astype(float)

print("orginal array:", int_array)
print("converted to float:", float_array)

orginal array: [1 2 3 4]
converted to float: [1. 2. 3. 4.]


# 6.Celsius to Fahrenheit Conversion

In [23]:
celsius_1 = np.array([0, 12, 45.21, 34, 99.91])
celsius_2 = np.array( [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ])

fahrenheit_1 = (celsius_1 * 9/5) + 32
fahrenheit_2 = (celsius_2 * 9/5) + 32

print("Values in Fahrenheit:", fahrenheit_1)
print("Values in Centigrade:", celsius_2)

Values in Fahrenheit: [ 32.     53.6   113.378  93.2   211.838]
Values in Celsius: [-17.78 -11.11   7.34   1.11  37.73   0.  ]


# 7.Append Values to Array (Do self-study)

In [30]:
arr = np.arange(10,40,10)
new_arr = np.append(arr, np.arange(40,100,10))

print("Original array: ", arr)
print("Appended version: ", new_arr)

Original array:  [10 20 30]
Appended version:  [10 20 30 40 50 60 70 80 90]


# 8. Array Statistical Functions (Do self-study)

In [35]:
random_ints = np.random.randint(1, 100, size=10)

mean = np.mean(random_ints)
median = np.median(random_ints)
std_dev = np.std(random_ints)

print(random_ints)
print(mean)
print(median)
print(std_dev)

[51 63 41 31  9 37  9  8 12 84]
34.5
34.0
24.707286374670936


# 9.Find min and max

In [52]:
random_ints2 = np.random.randint(0, 100, size=(10,10))
max_value = np.max(random_ints2)
min_value = np.min(random_ints2)


print(random_ints2)
print(max_value)
print(min_value)

[[58 63 97 50 22 88 46  0 10 21]
 [43  7 51 16 77 71 78  8 83 94]
 [ 8 84 73 39 83 36 25 55 95 85]
 [66  3  3 15 49 73 97  5 51 70]
 [51 35 64 68  4 28 52  6 88 78]
 [68 57 80 83 25 54  4 18 43  5]
 [66 69 73 62  2 64  3 38 10 96]
 [57 54 45 67  6  4 81 33 63 69]
 [56 35  8 71 89 98 73 43 95  0]
 [78 20 82  6 65 29 29 15 25 90]]
98
0


# 10.Create a 3x3x3 array with random values.

In [61]:
random_ints3 = np.random.randint(1, 30, size=(3,3,3))
print(random_ints3)

[[[25 28 26]
  [ 2  8 10]
  [ 4 24 24]]

 [[26 21 24]
  [25 17 25]
  [27 26 21]]

 [[16 15  6]
  [25  3 22]
  [28 24  7]]]
